### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by p16i** [COVID19-TCDG/datasets#1]
If I understand README.md correctly, these data files are updated everyday manually.

I think we can streamline the process by leveraging Travis CI, which allows us to set a CRON job.

My ideas are the following:
- everyday, Travis will run a job fetching all the data from all the sources.
- this data can be published on GitHub Page or be committed to `master`.

**Comment by ninyawee** [comment]
You are correct! 

Let me export my python environment first.

**Comment by ninyawee** [comment]
exported 903b8cbfa78cc7326d51370649a6ac6a8d9f006b

**Comment by ninyawee** [comment]
I'm not use to travis alot but I know github action. 

Do you mind to use github action instead?

**Comment by p16i** [comment]
we can also use Github Action. I didn't know that we can setup cron with Github Action.

Please see https://jasonet.co/posts/scheduled-actions/.

**Comment by ninyawee** [comment]
Do you mind doing PR? I can help with scheduling. 
FYI <https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule>

**Comment by ninyawee** [comment]
I will take that as no. It is ok.
1. for 5lab dataset is fully automated
2. but thstat dataset require human to download for this moment.

**Comment by p16i** [comment]
I've found this source yesterday, and it seems official.

https://data.go.th/dataset/covid-19-daily 

Currently, I'm working on another project, probably won't have time to make a PR.

**Comment by ninyawee** [comment]
> I've found this source yesterday, and it seems official.
> 
> [data.go.th/dataset/covid-19-daily](https://data.go.th/dataset/covid-19-daily)
> 
> Currently, I'm working on another project, probably won't have time to make a PR.

That was included in `README.md` since f36a8ae3be7b222a577e7b2385d5b2b6cd3d7fad. 

It is ok. Thank you for helping to shape our repo. Suggestions are always welcome.

**Comment by p16i** [comment]
ahh, I didn't that. sorry for that :(.

I've also made this script: https://gist.github.com/heytitle/e30017778257bc514cbb970068e9f38f.
<img width="413" alt="Screen Shot 2020-03-22 at 9 14 57 AM" src="https://user-images.githubusercontent.com/1214890/77245313-ecbecc80-6c1d-11ea-8e81-fc0f2f54df70.png">
