### ISSUE TITLE
🦠 Ingest data to BigQuery

### ISSUE THREAD

**Issue by katopz** [COVID19-TCDG/datasets#11]
- [x] https://github.com/COVID19-TCDG/datasets/blob/master/datasets/5lab.csv
- [x] https://github.com/COVID19-TCDG/datasets/blob/master/datasets/thstat.csv

Self assign to me, will finish this tmr :) @katopz

**Comment by ninyawee** [comment]
Gladly accepted 😉 Thank you

**Comment by katopz** [comment]
https://console.cloud.google.com/bigquery?project=nl-covid&p=nl-covid&d=tcgd&t=5lab20200324&page=table

https://console.cloud.google.com/bigquery?project=nl-covid&p=nl-covid&d=tcgd&t=thstat20200324&page=table

![image](https://user-images.githubusercontent.com/97060/77413911-c00fde00-6df2-11ea-83be-255d50afcb9d.png)

https://github.com/katopz/nl-covid/blob/master/firebase/functions/src/tcgd/index.ts

Consider it done :)

**Comment by ninyawee** [comment]
@katopz access denied krub 
![Screenshot 2020-03-24 at 8 41 12 PM](https://user-images.githubusercontent.com/8089231/77431816-d0828180-6e0f-11ea-97f4-112c79a50fd5.png)

**Comment by katopz** [comment]
@CircleOnCircles  Permission granted, should work now. Please try again

**Comment by ninyawee** [comment]
Still another error
![Screenshot 2020-03-24 at 10 42 25 PM](https://user-images.githubusercontent.com/8089231/77446245-be5d0f00-6e20-11ea-9314-86daace25258.png)

**Comment by ninyawee** [comment]
@katopz  How often do another ingest - the workpoint run?

**Comment by katopz** [comment]
Job create is not allow because it's meant to be read only for security reason :)
Anyway, I decide to donate cloud credit for help us in this situation.

Please provide me your google email, I will grant a DML permission for you.

> @katopz How often do another ingest - the workpoint run?

Manual daily by now because their schema keep changing every day so it will break schedule anyway. ;p

**Comment by ninyawee** [comment]
> Job create is not allow because it's meant to be read only for security reason :)
> Anyway, I decide to donate cloud credit for help us in this situation.
> 
> Please provide me your google email, I will grant a DML permission for you.
> 
> > @katopz How often do another ingest - the workpoint run?
> 
> Manual daily by now because their schema keep changing every day so it will break schedule anyway. ;p

Thank you for that. I forgot 😅 to set the project so that it alerts the error. Thank you for your contributions. 👍

**Comment by ninyawee** [comment]
close as 1281d5bb8b46b16be049be3744feac91eca10f21
